Bootstrap: docker

From: nvidia/cuda:11.1.1-base-ubuntu20.04

%post

    apt-get update && apt-get install -y software-properties-common
    add-apt-repository ppa:deadsnakes/ppa
    apt-get update && apt-get install -y \
    python3.7 \
    git \
    curl \
        && rm -rf /var/lib/apt/lists/*
    curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    ln -s /usr/bin/python3.7 /usr/bin/python
    python --version
    python get-pip.py
    pip install torch==1.0.1
    pip install torchvision==0.2.2
    mkdir workspace
    git clone https://github.com/yuhuixu1993/PC-DARTS.git /workspace/PC-DARTS
    cp /workspace/PC-DARTS/V100_python1.0/train.py /workspace/PC-DARTS/
    cp /workspace/PC-DARTS/V100_python1.0/train_search.py /workspace/PC-DARTS/
