Bootstrap: docker

From: nvidia/cuda:11.1.1-base-ubuntu20.04

%post

    apt-get update && apt-get install -y \
    python2.7 \
    git \
    curl \
        && rm -rf /var/lib/apt/lists/*
    curl -sSL https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
    python2.7 get-pip.py
    pip install torch==0.3.1
    pip install torchvision==0.2.1
    ln -s /usr/bin/python2.7 /usr/bin/python
    mkdir workspace
    git clone https://github.com/yuhuixu1993/PC-DARTS.git /workspace/PC-DARTS